name: webApp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.109.0
  - uvicorn=0.27.1
  - geopandas=1.0.1
  - fiona=1.9.6
  - shapely=2.0.3
  - rasterio=1.4.2
  - pip
  - pip:
      - zipfile2==0.0.12
      - python-multipart==0.0.9
